# Generated by Django 4.1.2 on 2022-10-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameModel',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='ProfileModel',
            new_name='Profile',
        ),
    ]
