# Generated by Django 4.1.2 on 2022-10-23 10:04

import FitnessWebsite.trainers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(upload_to='media', validators=[FitnessWebsite.trainers.validators.validate_file_size]),
        ),
    ]
