# Generated by Django 4.1.2 on 2022-10-23 10:45

import FitnessWebsite.trainers.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_alter_trainer_photo'),
        ('trainings', '0003_training_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='photo',
            field=models.ImageField(default=None, upload_to='media', validators=[FitnessWebsite.trainers.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer'),
        ),
    ]
