# Generated by Django 4.1.1 on 2022-10-22 12:41

import Petstragram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[Petstragram.photos.validators.validate_file_size]),
        ),
    ]
