# Generated by Django 4.1.2 on 2022-10-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_employees_department_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='level',
            field=models.CharField(choices=[('jr.', 'Junior'), ('mid.', 'Middle'), ('sr.', 'Senior')], max_length=4, verbose_name='Seniority level'),
        ),
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.department'),
        ),
    ]
