# Generated by Django 4.1.2 on 2022-10-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_department_alter_employees_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='department',
        ),
    ]
