# Generated by Django 4.1.2 on 2022-10-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_project_employees_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='code_name',
            new_name='deadline',
        ),
    ]
